#!/usr/bin/env python3
"""Flatten AGENTS.md and its `@` imports into one self-contained document.

Claude expands `@path` imports into context itself, so it needs nothing from this script.
Codex and opencode do not: each reads its global AGENTS.md literally, and an `@` line
arrives as a suggestion the model may or may not follow with a file read (measured: Codex
logs "Checking imported instruction" and shells out, but only when it thinks it matters).
Anything load-bearing therefore has to be literal text in their file, which means one
source has to be resolved into three fixed destinations, and no harness does that part.

Regions fenced with `<!-- claude-only -->` / `<!-- /claude-only -->` are dropped here and
kept for Claude, which reads the sources directly. Use it for guidance that is false
elsewhere, such as a page describing a Claude Code hook.

Writes to stdout. `--check` exits non-zero if stdout would differ from a given file,
so setup can tell a stale copy from a current one. `--install` writes the render into
every harness's global file as a marker-scoped block, leaving other owners of those files
alone, and rewrites nothing when the content already matches.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DOTFILES = Path(__file__).resolve().parent.parent
HUB = DOTFILES / "AGENTS.md"
CACHE = DOTFILES / "agents-global.local.md"

# Fixed paths, because that is the only global slot each harness has: Codex reads no
# AGENTS.md above a repo root (measured: a canary one directory up is not seen, with or
# without a git repo), so there is nowhere else to put this.
XDG = Path.home() / ".config"
TARGETS = (Path.home() / ".codex" / "AGENTS.md", XDG / "opencode" / "AGENTS.md")

BLOCK_ID = "global-context"
# The narrower block this one supersedes. markdown_block_set only ever removes its own id,
# so without an explicit purge the old copy would sit below the new one forever.
LEGACY_IDS = ("agent-integrations",)

# `@path` alone on a line is an import. Anything else on the line is prose, not a directive.
IMPORT = re.compile(r"^@(\S+)\s*$")
CLAUDE_ONLY = re.compile(r"^[ \t]*<!--[ \t]*claude-only[ \t]*-->.*?^[ \t]*<!--[ \t]*/claude-only[ \t]*-->[ \t]*\n?",
                        re.DOTALL | re.MULTILINE)


def flatten(path: Path, seen: frozenset[Path] = frozenset()) -> str:
    """Inline every import of `path`, resolving each one relative to its own file."""
    path = path.resolve()
    if path in seen:                      # a cycle would otherwise recurse forever
        return ""
    if not path.is_file():
        # A missing import is a real defect: the whole point is that the copy is complete.
        # Loud in the output, because a silent gap reads as "this rule does not exist".
        return f"<!-- MISSING IMPORT: {path} (run setup.sh) -->\n"

    out: list[str] = []
    for line in CLAUDE_ONLY.sub("", path.read_text()).splitlines(keepends=True):
        match = IMPORT.match(line)
        if match:
            target = (path.parent / match.group(1)).resolve()
            body = flatten(target, seen | {path}).strip("\n")
            if body:
                out.append(body + "\n")
        else:
            out.append(line)
    return "".join(out)


def render() -> str:
    body = flatten(HUB).strip("\n")
    header = (
        "<!-- Generated by scripts/render-global-context.py from AGENTS.md. Do not edit here:\n"
        "     edit the hub in the dotfiles repo and re-run setup.sh. -->\n\n"
    )
    return header + body + "\n"


def strip_block(text: str, block_id: str) -> str:
    """Remove every instance of one marker-scoped block, keeping the rest of the file."""
    start = f"<!-- >>> dotfiles:{block_id} >>> -->"
    end = f"<!-- <<< dotfiles:{block_id} <<< -->"
    while start in text:
        before, rest = text.split(start, 1)
        if end not in rest:                # truncated block: drop the tail, it is unowned
            return before.rstrip("\n") + "\n"
        text = before.rstrip("\n") + rest.split(end, 1)[1]
    return text


def install(body: str) -> list[str]:
    """Write the block into each harness's global file. Returns the paths actually changed."""
    block = f"<!-- >>> dotfiles:{BLOCK_ID} >>> -->\n{body.strip()}\n<!-- <<< dotfiles:{BLOCK_ID} <<< -->"
    changed = []
    for target in TARGETS:
        original = target.read_text() if target.is_file() else ""
        text = strip_block(original, BLOCK_ID)
        for legacy in LEGACY_IDS:
            text = strip_block(text, legacy)
        text = text.rstrip("\n")
        text = f"{text}\n\n{block}\n" if text else f"{block}\n"
        if text != original:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text)
            changed.append(str(target))
    return changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", metavar="FILE", help="exit 1 if FILE differs from the render")
    parser.add_argument("--install", action="store_true",
                        help="write the render into every harness global file, and cache it")
    parser.add_argument("--quiet", action="store_true", help="with --install, print nothing")
    args = parser.parse_args()

    text = render()
    if args.check:
        current = Path(args.check)
        if not current.is_file() or current.read_text() != text:
            print(f"stale: {args.check} does not match AGENTS.md", file=sys.stderr)
            return 1
        return 0

    if args.install:
        if not CACHE.is_file() or CACHE.read_text() != text:
            CACHE.write_text(text)
        changed = install(text)
        if not args.quiet:
            print(f"global context -> {', '.join(changed)}" if changed
                  else "global context already current in every harness file")
        return 0

    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
