#!/usr/bin/env bash
# Onboard one repo into the SlayZone + T3 Code pair. Idempotent: safe to re-run.
#
# The seam this automates: SlayZone owns the board, the per-task worktree, and shipping;
# T3 Code owns the conversation and diff review over that SAME worktree. Every step below
# exists to keep those two from each cutting their own checkout of the same repo.
set -euo pipefail

REPO="$(cd "${1:-$PWD}" && pwd)"
NAME="${2:-$(basename "$REPO")}"
T3_SETTINGS="$HOME/.t3/userdata/settings.json"

say() { printf '  %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

command -v slay >/dev/null 2>&1 || die "slay CLI not found — run setup.sh"
git -C "$REPO" rev-parse --git-dir >/dev/null 2>&1 || die "not a git repo: $REPO"

# 1. SlayZone project (keyed by name; update the path if it drifted)
if slay projects list --json | jq -e --arg n "$NAME" 'any(.[]; .name == $n)' >/dev/null; then
  slay projects update "$NAME" --path "$REPO" >/dev/null
  say "slay project '$NAME' already existed — path re-pointed at $REPO"
else
  slay projects create "$NAME" --path "$REPO" >/dev/null
  say "slay project '$NAME' -> $REPO"
fi

# 2. Built-in slay skills, so an agent in a task terminal can drive the board
slay init skills -p "$NAME" >/dev/null && say "slay skills installed"

# 3. SlayZone environment instructions into the repo's agent files. Marker-guarded:
#    the block is regenerated by the CLI, so appending twice would just duplicate it.
#    The dotfiles repo is skipped on purpose: its CLAUDE.md is the GLOBAL instruction hub
#    (~/.claude/CLAUDE.md @-imports it), so a per-project block there would load into every
#    session on the box, including ones with no SlayZone task anywhere near them.
DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
for f in AGENTS.md CLAUDE.md; do
  path="$REPO/$f"
  [ -f "$path" ] || continue
  if [ "$REPO" = "$DOTFILES_ROOT" ] && [ "$f" = "CLAUDE.md" ]; then
    say "skipped CLAUDE.md — it is the global instruction hub, not a project file"
    continue
  fi
  if grep -q "^# SlayZone Environment" "$path"; then
    say "$f already carries the SlayZone block"
  else
    { printf '\n'; slay init instructions -p "$NAME"; } >> "$path"
    say "$f += SlayZone environment block"
  fi
done

# 4. The actual glue: when a task starts, hand ITS worktree to T3 as a project. Without
#    this you open T3 at the repo root and review the main checkout while the agent works
#    in the task's worktree — the diffs silently belong to different trees.
AUTOMATION="t3-project"
if slay automations list --project "$NAME" --json | jq -e --arg n "$AUTOMATION" 'any(.[]; .name == $n)' >/dev/null; then
  say "automation '$AUTOMATION' already present"
else
  slay automations create "$AUTOMATION" --project "$NAME" \
    --trigger task_status_change --trigger-to-status in_progress \
    --description "Register the task worktree as a T3 Code project" \
    --action-command 't3 project add "{{task.worktree_path}}" --title "{{task.name}}"' >/dev/null
  say "automation '$AUTOMATION' created (in_progress -> t3 project add)"
fi

# 5. Pin T3 new threads to the current checkout. "local" is already T3's default, so this
#    only guards against a flipped setting later — a worktree-mode thread would cut a
#    SECOND checkout of a repo SlayZone has already isolated.
if [ -f "$T3_SETTINGS" ]; then
  tmp="$(mktemp)"
  jq '.defaultThreadEnvMode = "local"' "$T3_SETTINGS" > "$tmp" && mv "$tmp" "$T3_SETTINGS"
  say "T3 defaultThreadEnvMode pinned to local"
else
  say "T3 settings not found (launch T3 once) — defaultThreadEnvMode already defaults to local"
fi

printf '\nDone. Next: slay tasks create "..." --project %s, then open T3 from the task terminal.\n' "$NAME"
